/** Canonical provider identities. Discovery feeds are inconsistent, so callers
 * resolve through this catalogue instead of deriving a slug from raw text. */
export interface ProviderDefinition { slug:string; name:string; adapterKey:string; adapterCapability:"AUTOMATED"|"PARTIAL"|"MANUAL"; }
export const providerDefinitions:readonly ProviderDefinition[]=[
  {slug:"groq",name:"Groq",adapterKey:"openai-compatible",adapterCapability:"AUTOMATED"},{slug:"cerebras",name:"Cerebras",adapterKey:"openai-compatible",adapterCapability:"AUTOMATED"},{slug:"nvidia",name:"NVIDIA NIM",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},
  {slug:"google-ai-studio",name:"Google AI Studio",adapterKey:"google-ai-studio",adapterCapability:"PARTIAL"},{slug:"vertex-ai",name:"Google Cloud Vertex AI",adapterKey:"vertex-ai",adapterCapability:"MANUAL"},{slug:"openrouter",name:"OpenRouter",adapterKey:"openrouter",adapterCapability:"AUTOMATED"},{slug:"mistral",name:"Mistral",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"sambanova",name:"SambaNova",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"cohere",name:"Cohere",adapterKey:"cohere",adapterCapability:"MANUAL"},
  {slug:"hugging-face",name:"Hugging Face Inference",adapterKey:"manual",adapterCapability:"PARTIAL"},{slug:"cloudflare-workers-ai",name:"Cloudflare Workers AI",adapterKey:"manual",adapterCapability:"PARTIAL"},{slug:"alibaba-model-studio",name:"Alibaba Cloud Model Studio",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"zhipu",name:"Z.AI / Zhipu",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"volcengine-ark",name:"Volcengine Ark",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"gigachat",name:"GigaChat",adapterKey:"gigachat",adapterCapability:"MANUAL"},
  {slug:"together-ai",name:"Together AI",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"public-ai",name:"PublicAI",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"sarvam",name:"Sarvam AI",adapterKey:"sarvam",adapterCapability:"MANUAL"},
  {slug:"deepseek",name:"DeepSeek",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},{slug:"minimax",name:"MiniMax",adapterKey:"openai-compatible",adapterCapability:"PARTIAL"},
  // Lemonade is a self-hosted OpenAI-compatible server, not a credential vendor.
  {slug:"lemonade",name:"Lemonade Server",adapterKey:"openai-compatible",adapterCapability:"MANUAL"},{slug:"ibm-watsonx",name:"IBM watsonx.ai",adapterKey:"manual",adapterCapability:"MANUAL"},{slug:"kilo",name:"Kilo",adapterKey:"manual",adapterCapability:"MANUAL"},{slug:"vercel-ai-gateway",name:"Vercel AI Gateway",adapterKey:"manual",adapterCapability:"MANUAL"},{slug:"opencode-zen",name:"OpenCode Zen",adapterKey:"manual",adapterCapability:"MANUAL"},{slug:"llm7",name:"LLM7",adapterKey:"manual",adapterCapability:"MANUAL"},{slug:"local",name:"Local OpenAI-compatible",adapterKey:"openai-compatible",adapterCapability:"MANUAL"},
] as const;
const bySlug=new Map(providerDefinitions.map(item=>[item.slug,item]));
const aliases:Readonly<Record<string,string>>={gemini:"google-ai-studio",google:"google-ai-studio",google_ai_studio:"google-ai-studio",nvidia_nim:"nvidia",huggingface:"hugging-face",hugging_face:"hugging-face",cloudflare:"cloudflare-workers-ai",cloudflare_ai:"cloudflare-workers-ai",watsonx:"ibm-watsonx",watsonx_ai:"ibm-watsonx",zai:"zhipu",zhipuai:"zhipu",z_ai:"zhipu",codestral:"mistral",together_ai:"together-ai",publicai:"public-ai",volcengine:"volcengine-ark",vertex_ai:"vertex-ai",vertex_ai_llama_models:"vertex-ai",vercel_ai_gateway:"vercel-ai-gateway"};
const normalized=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
/** Resolve source metadata and bare community model IDs to a known provider. */
export function resolveProvider(providerName:string|null|undefined,modelRef:string):ProviderDefinition|null {const raw=normalized(providerName??"");const candidate=aliases[raw]??aliases[raw.replaceAll("-","_")]??raw;if(candidate&&bySlug.has(candidate))return bySlug.get(candidate)??null;const model=modelRef.trim().toLowerCase();const prefix=model.split("/",1)[0]??"";const mappedPrefix=aliases[normalized(prefix)]??normalized(prefix);if(bySlug.has(mappedPrefix))return bySlug.get(mappedPrefix)??null;if(/^(?:zai-org\/)?glm[-_]/.test(model))return bySlug.get("zhipu")??null;if(/^(?:qwen|tongyi)[-_]/.test(model))return bySlug.get("alibaba-model-studio")??null;return null;}
export function providerSlug(providerName:string|null|undefined,modelRef:string):string|null{return resolveProvider(providerName,modelRef)?.slug??null;}
