import "server-only";
import { and, eq } from "drizzle-orm";
import { decryptCredential } from "@/server/credentials/crypto";
import { getDb } from "@/server/db/client";
import { providerCredentialReferences,providers } from "@/server/db/schema";

const endpoints:Readonly<Record<string,{url:string;auth:"bearer"|"query"}>>={
  groq:{url:"https://api.groq.com/openai/v1/models",auth:"bearer"},cerebras:{url:"https://api.cerebras.ai/v1/models",auth:"bearer"},nvidia:{url:"https://integrate.api.nvidia.com/v1/models",auth:"bearer"},"google-ai-studio":{url:"https://generativelanguage.googleapis.com/v1beta/models",auth:"query"},openrouter:{url:"https://openrouter.ai/api/v1/auth/key",auth:"bearer"},mistral:{url:"https://api.mistral.ai/v1/models",auth:"bearer"},sambanova:{url:"https://api.sambanova.ai/v1/models",auth:"bearer"},cohere:{url:"https://api.cohere.com/v1/models",auth:"bearer"},"hugging-face":{url:"https://huggingface.co/api/whoami-v2",auth:"bearer"},"opencode-zen":{url:"https://opencode.ai/zen/v1/models",auth:"bearer"},llm7:{url:"https://api.llm7.io/v1/models",auth:"bearer"},"alibaba-model-studio":{url:"https://dashscope.aliyuncs.com/compatible-mode/v1/models",auth:"bearer"},zhipu:{url:"https://open.bigmodel.cn/api/paas/v4/models",auth:"bearer"},
};

export const supportsCredentialTest = (slug: string) => Boolean(endpoints[slug]);

export async function verifyProvider(providerId:string){const db=getDb();const provider=(await db.select().from(providers).where(eq(providers.id,providerId)).limit(1))[0];if(!provider)throw new Error("Provider not found");if(!provider.enabled)return {supported:true,ok:false,message:"Enable the provider before testing its credential"};const definition=endpoints[provider.slug];if(!definition)return{supported:false,ok:false,message:"This adapter does not expose a safe credential check yet"};const credential=(await db.select().from(providerCredentialReferences).where(and(eq(providerCredentialReferences.providerId,providerId),eq(providerCredentialReferences.disabled,false))).limit(1))[0];if(!credential)throw new Error("No credential configured");let secret:string;if(credential.encryptedValue)secret=decryptCredential(credential.encryptedValue);else{secret=process.env[credential.environmentVariable]??"";if(!secret)throw new Error(`${credential.environmentVariable} is not available to the server`)}const url=definition.auth==="query"?`${definition.url}?key=${encodeURIComponent(secret)}`:definition.url;let response:Response;try{response=await fetch(url,{headers:{accept:"application/json",...(definition.auth==="bearer"?{authorization:`Bearer ${secret}`}:{})},signal:AbortSignal.timeout(20_000),cache:"no-store"})}catch{await db.update(providers).set({status:"DEGRADED",updatedAt:new Date()}).where(eq(providers.id,providerId));return{supported:true,ok:false,message:"Connection failed. Check provider availability and server network connectivity."}}const ok=response.ok;const authFailure=response.status===401||response.status===403;await db.update(providerCredentialReferences).set({valid:ok?true:authFailure?false:null,lastValidatedAt:new Date(),updatedAt:new Date()}).where(eq(providerCredentialReferences.id,credential.id));await db.update(providers).set({status:ok?"ACTIVE":authFailure?"AUTH_FAILED":"DEGRADED",updatedAt:new Date()}).where(eq(providers.id,providerId));return{supported:true,ok,status:response.status,message:ok?"Credential verified":authFailure?"Provider rejected the credential":`Provider returned HTTP ${response.status}`};}
