import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { StatusPill } from "@/components/status-pill";
import { timeAgo } from "@/lib/utils";
import { demoDeployments } from "@/server/demo-data";
import { getDeployments,getModelCandidates,withDemo } from "@/server/queries";
import { getCandidateProviderPortal } from "@/server/providers/portals";
import { DiscoveryButton } from "./discovery-button";
import { ConnectCandidateButton } from "./connect-button";

export const dynamic="force-dynamic";
export default async function ModelsPage(){const[rows,candidates]=await Promise.all([withDemo(getDeployments,()=>demoDeployments),getModelCandidates()]);return <PageShell title="Models" eyebrow={`${rows.length} live deployments · ${candidates.length} discovery observations`} actions={<DiscoveryButton/>}><section className="panel" style={{marginBottom:14}}><div className="panel-header"><h3>Discovered free-model candidates</h3><span>Provider credentials are linked by normalized provider identity</span></div><table className="data-table"><thead><tr><th>Candidate</th><th>Provider / credential</th><th>Source</th><th>Free evidence</th><th>Context</th><th>Action</th></tr></thead><tbody>{candidates.length?candidates.map(row=>{const portal=getCandidateProviderPortal(row.source,row.providerName,row.modelRef);return <tr key={row.id}><td><strong>{row.displayName}</strong><br/><span className="mono">{row.modelRef}</span></td><td>{row.providerName??"Unresolved"}{portal?<><br/><a href={portal.url} target="_blank" rel="noopener noreferrer">{portal.label} ↗</a><br/><StatusPill value={row.credentialVerified?"Credential verified":row.credentialConfigured?"Credential unverified":"Credential missing"}/></>:<><br/><span style={{color:"var(--faint)",fontSize:10}}>No verified provider portal</span></>}</td><td><a href={row.sourceUrl??"#"} target="_blank" rel="noopener noreferrer">{row.source}</a></td><td><StatusPill value={row.verifiedFree?row.freeType:"UNVERIFIED"}/></td><td className="mono">{row.contextWindow?.toLocaleString()??"—"}</td><td><ConnectCandidateButton candidateId={row.id} disabled={!portal||!row.credentialVerified}/></td></tr>}):<tr><td colSpan={6}>No candidates stored. Run discovery to query the live sources.</td></tr>}</tbody></table></section><section className="panel"><div className="panel-header"><h3>Live LiteLLM deployments</h3><span>Not assumed free unless evidence exists</span></div><table className="data-table"><thead><tr><th>Model</th><th>Alias</th><th>Provider / backend</th><th>Free status</th><th>Ownership</th><th>Health</th><th>RPM / TPM</th><th>Last tested</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link href={`/models/${row.id}`}><strong>{row.modelName}</strong><br/><span className="mono">{row.providerModelId}</span></Link></td><td className="mono">{row.litellmModelName}</td><td>{row.providerName}{row.backend?<><br/><span className="mono">{row.backend}</span></>:null}</td><td><StatusPill value={row.freeType}/></td><td><span className={row.managed?"managed-badge":"unmanaged-badge"}>{row.managed?"Managed":"Unmanaged"}</span></td><td><StatusPill value={row.health}/></td><td className="mono">{row.safeRpm??row.rpmLimit??"—"} / {row.safeTpm??row.tpmLimit??"—"}</td><td>{timeAgo(row.lastTestedAt)}</td></tr>)}</tbody></table></section></PageShell>}
