import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { StatusPill } from "@/components/status-pill";
import { duration, timeAgo } from "@/lib/utils";
import { demoDeployments } from "@/server/demo-data";
import { getDeployment, withDemo } from "@/server/queries";
import { SmokeButton } from "./smoke-button";
import { DeploymentActions } from "@/app/litellm/deployment-actions";

export const dynamic="force-dynamic";
export default async function ModelDetail({params}:{params:Promise<{id:string}>}) { const {id}=await params; const row=await withDemo(()=>getDeployment(id),()=>demoDeployments.find(item=>item.id===id)??null); if(!row)notFound(); return <PageShell title={row.modelName} eyebrow={`${row.providerName} · ${row.providerModelId}`} actions={<SmokeButton deploymentId={row.id} model={row.litellmModelName}/>}><div className="detail-grid"><section className="panel"><div className="panel-header"><h3>Deployment</h3><div style={{display:"flex",alignItems:"center",gap:12}}><StatusPill value={row.health}/><DeploymentActions id={row.id} alias={row.litellmModelName} health={row.health} live={Boolean(row.litellmDeploymentId)}/></div></div><div className="panel-body"><dl className="definition-list"><dt>Canonical model</dt><dd>{row.slug}</dd><dt>Provider deployment</dt><dd>{row.providerModelId}</dd><dt>LiteLLM alias</dt><dd>{row.litellmModelName}</dd><dt>Ownership</dt><dd>{row.managed?"Managed by RatLLM":"Unmanaged · read only"}</dd><dt>Score</dt><dd>{row.score?.toFixed(1)??"Not scored"}</dd><dt>Last tested</dt><dd>{timeAgo(row.lastTestedAt)}</dd></dl></div></section><section className="panel"><div className="panel-header"><h3>Rate limit evidence</h3><StatusPill value={row.confidence}/></div><div className="panel-body metric-card-grid"><div className="metric-card"><small>Documented</small><strong>{row.rpmLimit??"—"} RPM</strong><p>{row.tpmLimit?.toLocaleString()??"—"} TPM · fact</p></div><div className="metric-card"><small>Observed</small><strong>— RPM</strong><p>Insufficient rolling evidence</p></div><div className="metric-card"><small>Safe configured</small><strong>{row.safeRpm??"—"} RPM</strong><p>{row.safeTpm?.toLocaleString()??"—"} TPM · estimate</p></div></div><p style={{fontSize:10,color:"var(--muted)",marginTop:14}}>Manual overrides are never replaced by learned estimates. Safe limits apply a conservative configurable margin.</p></section></div><section className="panel" style={{marginTop:14}}><div className="panel-header"><h3>Capabilities and observations</h3><span>Normalized metadata</span></div><div className="panel-body"><p style={{color:"var(--muted)",fontSize:11}}>Capability evidence will appear after deterministic benchmark suites complete. This deployment was last measured {timeAgo(row.lastTestedAt)}; latency {duration(null)}.</p></div></section></PageShell> }
