CREATE TYPE "automation_status" AS ENUM ('IDLE', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DISABLED');--> statement-breakpoint
CREATE TYPE "source_type" AS ENUM ('PROVIDER_API', 'OPENAI_COMPATIBLE', 'JSON_FEED', 'MANUAL', 'CUSTOM_ADAPTER');--> statement-breakpoint
ALTER TABLE "provider_credential_references" ADD COLUMN IF NOT EXISTS "disabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "provider_credential_references" ADD COLUMN IF NOT EXISTS "last_used_at" timestamp with time zone;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "automation_jobs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "type" text NOT NULL UNIQUE, "enabled" boolean DEFAULT true NOT NULL, "schedule" text NOT NULL, "timezone" text DEFAULT 'UTC' NOT NULL, "status" "automation_status" DEFAULT 'IDLE' NOT NULL, "last_run_at" timestamp with time zone, "next_run_at" timestamp with time zone, "duration_ms" integer, "failure_count" integer DEFAULT 0 NOT NULL, "last_error" text, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "automation_jobs_due_idx" ON "automation_jobs" ("enabled", "next_run_at");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "model_sources" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" text NOT NULL, "type" "source_type" NOT NULL, "provider_id" uuid REFERENCES "providers"("id") ON DELETE set null, "url" text, "enabled" boolean DEFAULT true NOT NULL, "priority" integer DEFAULT 100 NOT NULL, "credential_reference" text, "adapter_reference" text, "last_sync_at" timestamp with time zone, "status" text DEFAULT 'UNKNOWN' NOT NULL, "discovered_model_count" integer DEFAULT 0 NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "api_keys" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" text NOT NULL, "key_hash" text NOT NULL UNIQUE, "prefix" text NOT NULL, "fingerprint" text NOT NULL, "scopes" jsonb DEFAULT '[]'::jsonb NOT NULL, "expires_at" timestamp with time zone, "last_used_at" timestamp with time zone, "revoked_at" timestamp with time zone, "replaced_by_id" uuid, "grace_until" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_prefix_idx" ON "api_keys" ("prefix");
