import "server-only";
import { randomUUID } from "node:crypto";
import { eq,and } from "drizzle-orm";
import { getDb } from "@/server/db/client";
import { auditEvents,modelCandidates,providers,syncRuns } from "@/server/db/schema";
import { discoverySources } from "./sources";
import { resolveProvider } from "@/server/providers/catalog";

export async function runDiscovery(){const db=getDb();const correlationId=randomUUID();const[run]=await db.insert(syncRuns).values({type:"MODEL_DISCOVERY",status:"RUNNING",correlationId,startedAt:new Date()}).returning();const results=await Promise.allSettled(discoverySources.map(async source=>({source:source.id,items:await source.discover()})));let discovered=0;const sources=[];for(const result of results){if(result.status==="rejected"){sources.push({status:"failed",error:result.reason instanceof Error?result.reason.message:"Unknown source error"});continue}const{source,items}=result.value;sources.push({source,status:"succeeded",count:items.length});for(const item of items){const provider=resolveProvider(item.providerName,item.modelRef);if(provider){await db.insert(providers).values(provider).onConflictDoNothing();item.providerName=provider.name;}const existing=(await db.select({id:modelCandidates.id,evidence:modelCandidates.evidence}).from(modelCandidates).where(and(eq(modelCandidates.source,item.source),eq(modelCandidates.modelRef,item.modelRef))).limit(1))[0];const values={displayName:item.displayName,providerName:item.providerName??null,lifecycle:"DISCOVERED" as const,freeType:item.freeType,verifiedFree:item.verifiedFree,contextWindow:item.contextWindow??null,maxOutputTokens:item.maxOutputTokens??null,supportsVision:item.supportsVision??null,supportsTools:item.supportsTools??null,supportsReasoning:item.supportsReasoning??null,sourceUrl:item.sourceUrl,evidence:{...(existing?.evidence??{}),...item.evidence},lastSeenAt:new Date(),updatedAt:new Date()};if(existing)await db.update(modelCandidates).set(values).where(eq(modelCandidates.id,existing.id));else await db.insert(modelCandidates).values({source:item.source,modelRef:item.modelRef,...values});discovered++}}const failed=results.filter(r=>r.status==="rejected").length;const summary={discovered,sources};await db.update(syncRuns).set({status:failed===results.length?"FAILED":"SUCCEEDED",summary,finishedAt:new Date(),updatedAt:new Date()}).where(eq(syncRuns.id,run.id));await db.insert(auditEvents).values({actor:"system",action:"discovery.completed",entityType:"sync_run",entityId:run.id,after:summary,correlationId});return{runId:run.id,correlationId,...summary};}
