import Link from "next/link";
import { AlertTriangle, Cable, Database, ServerCog } from "@/components/icons";
import { StatusPill } from "@/components/status-pill";
import { Topbar } from "@/components/topbar";
import { formatSummary, timeAgo } from "@/lib/utils";
import { getDashboard } from "@/server/queries";
import { getOperationalStatus } from "@/server/operational-status";

export const dynamic = "force-dynamic";

export default async function OverviewPage() {
  const data = await getDashboard();
  // "Is RatLLM actually working?" — not just "is the page up?". Never let a failure here take the overview down.
  const operational = data.demo ? null : await getOperationalStatus().catch(() => null);
  const systems = [["CURATOR",data.systems.curator,ServerCog],["LITELLM",data.systems.litellm,Cable],["DATABASE",data.systems.database,Database]] as const;
  const kpis = [["Providers",data.kpis.providers,"configured","good"],["Discovered models",data.kpis.models,"across all providers",""],["Active deployments",data.kpis.active,"serving aliases","good"],["Providers healthy",data.providers.filter(provider=>provider.enabled !== false && provider.healthyCount > 0).length,"with healthy deployments","good"],["Quarantined",data.kpis.quarantined,"under observation",data.kpis.quarantined?"warn":""],["Healthy lanes",`${data.lanes.filter(lane=>lane.enabled && lane.status === "HEALTHY").length}/${data.lanes.filter(lane=>lane.enabled).length}`,"redundancy target",data.kpis.coverage>90?"good":"warn"],["24h 429s",data.kpis.errors429,"provider responses",data.kpis.errors429?"warn":"good"],["Pending changes",data.demo ? data.kpis.pendingChanges : "—",data.demo ? "awaiting review" : "plans not implemented",""]] as const;
  return <><Topbar showSearch={false}/><main className="page">
    {operational && operational.reasons.length > 0 && <section className="panel" style={{marginBottom:14,borderColor:operational.status==="degraded"?"var(--amber)":undefined}}><div className="panel-header"><h3>{operational.status==="degraded"?"Needs attention":"Notes"}</h3><span>{operational.reasons.filter(r=>r.severity==="degraded").length} issue{operational.reasons.filter(r=>r.severity==="degraded").length===1?"":"s"} · <a href="/api/status">details (JSON)</a></span></div><div className="panel-body"><ul style={{margin:0,paddingLeft:18,display:"grid",gap:4}}>{operational.reasons.map((reason,i)=><li key={i} style={{color:reason.severity==="degraded"?undefined:"var(--muted)"}}><strong className="mono" style={{fontSize:11}}>{reason.area}</strong> — {reason.message}</li>)}</ul></div></section>}
    {data.demo && <div className="demo-banner"><AlertTriangle size={13}/> Demo mode · realistic sample data is isolated from production persistence.</div>}
    <section className="system-strip">{systems.map(([name,status,Icon])=><div className="system-item" key={name}><Icon size={16}/><div><small>{name}</small><strong>{name === "CURATOR" ? "RatLLM Control Plane" : name === "DATABASE" ? "PostgreSQL" : "LiteLLM Proxy"}</strong></div><StatusPill value={status}/></div>)}</section>
    <section className="kpi-grid">{kpis.map(([label,value,detail,tone])=><div className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small className={tone}>{detail}</small></div>)}</section>
    <div className="content-grid">
      <section className="panel"><div className="panel-header"><h3>Lane health</h3><Link href="/lanes">Manage lanes →</Link></div><div className="panel-body lane-grid">{data.lanes.map(lane=>{const ratio=Math.min(100,lane.minimumHealthy?lane.healthy/lane.minimumHealthy*100:100);return <div className="lane-row" key={lane.slug}><div className="lane-name">{lane.slug}<small>{lane.total} assigned · {lane.total-lane.healthy} not healthy</small></div><div className={`bar ${ratio<100?"warn":""}`}><i style={{width:`${ratio}%`}}/></div><div className="lane-value"><strong>{lane.healthy} healthy</strong><small>{lane.status.replaceAll("_"," ")}</small></div></div>})}</div></section>
      <section className="panel"><div className="panel-header"><h3>Provider health</h3><Link href="/providers">View providers →</Link></div><div className="panel-body provider-list">{data.providers.slice(0,6).map(provider=><div className="provider-row" key={provider.id}><div className="provider-id"><span className="provider-icon">{provider.name.slice(0,2).toUpperCase()}</span><div><strong>{provider.name}</strong><small>{provider.credentialState ? `Credential ${provider.credentialState.toLowerCase()}` : provider.credentialConfigured ? "Credential configured" : "Credential missing"}</small></div></div><StatusPill value={provider.enabled === false ? "DISABLED" : provider.status}/><div className="provider-stat"><strong>{provider.healthyCount}/{provider.modelCount}</strong><small>healthy</small></div><div className="provider-stat"><strong>{provider.lastDiscoveryAt?timeAgo(provider.lastDiscoveryAt):"Manual"}</strong><small>discovery</small></div></div>)}</div></section>
    </div>
    <div className="content-grid">
      <section className="panel"><div className="panel-header"><h3>Recent activity</h3><Link href="/runs">Execution log →</Link></div><div className="panel-body flush"><table className="data-table"><thead><tr><th>Run</th><th>Type</th><th>Status</th><th>Summary</th><th>Started</th></tr></thead><tbody>{data.runs.map(run=>{const summary=formatSummary(run.summary);return <tr key={run.id}><td className="mono">{run.id.slice(0,8)}</td><td><strong>{run.type.replaceAll("_"," ")}</strong></td><td><StatusPill value={run.status}/></td><td><span className="truncate" title={summary}>{summary||"—"}</span></td><td>{timeAgo(run.createdAt)}</td></tr>})}</tbody></table></div></section>
      <section className="panel"><div className="panel-header"><h3>Needs attention</h3><span>{data.incidents.length} open</span></div><div className="panel-body attention-list">{data.incidents.length?data.incidents.map((incident,index)=><div className="attention" key={`${incident.title}-${index}`}><i/><div><strong>{incident.title}</strong><p>{incident.detail}</p></div><time>{timeAgo(incident.at)}</time></div>):<p style={{color:"var(--muted)",fontSize:11}}>No recorded problems. Check connection status and the latest test times in Settings.</p>}</div></section>
    </div>
  </main></>;
}
