import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { env } from "@/server/config";
import { getDb } from "@/server/db/client";
import { auditEvents, modelDeployments, smokeTests, syncRuns } from "@/server/db/schema";
import { apiError, correlationId } from "@/server/http";
import { HttpLiteLLMAdapter } from "@/server/litellm/client";
import { healthFromSmokeResult } from "@/server/status";
const bodySchema=z.object({deploymentId:z.string().min(1),model:z.string().min(1).max(300)});
export async function POST(request:Request){const id=correlationId(request);const parsed=bodySchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return apiError("INVALID_REQUEST","A deployment ID and model alias are required",400,id);if(env.DEMO_MODE)return NextResponse.json({ok:true,status:200,latencyMs:184,correlationId:id});const db=getDb();const deployment=(await db.select().from(modelDeployments).where(eq(modelDeployments.id,parsed.data.deploymentId)).limit(1))[0];if(!deployment)return apiError("DEPLOYMENT_NOT_FOUND","Deployment does not exist in Curator inventory",404,id);if(deployment.litellmModelName!==parsed.data.model)return apiError("MODEL_MISMATCH","Requested model does not match persisted deployment",409,id);// Probe the exact router deployment, like the scheduled monitor — an alias is shared by every member of its pool, so probing it would attribute the result to whichever member the router happened to pick. A removed deployment has no live ID and must not be probed at all.
if(deployment.lifecycle!=="ACTIVE"||!deployment.litellmDeploymentId)return apiError("DEPLOYMENT_NOT_LIVE","Deployment is not live in LiteLLM, so it cannot be tested",409,id);const[run]=await db.insert(syncRuns).values({type:"SMOKE_TEST",status:"RUNNING",correlationId:id,startedAt:new Date()}).returning();const result=await new HttpLiteLLMAdapter().smokeTest(deployment.litellmDeploymentId);await db.insert(smokeTests).values({runId:run.id,deploymentId:deployment.id,lane:deployment.litellmModelName,status:result.ok?"PASSED":"FAILED",latencyMs:result.latencyMs,firstTokenMs:result.firstTokenMs??null,httpStatus:result.status||null,error:result.error,responseExcerpt:result.content,correlationId:id});await db.update(modelDeployments).set({health:healthFromSmokeResult(result.ok,result.status),lastTestedAt:new Date(),updatedAt:new Date()}).where(eq(modelDeployments.id,deployment.id));await db.update(syncRuns).set({status:result.ok?"SUCCEEDED":"FAILED",finishedAt:new Date(),summary:{model:parsed.data.model,latencyMs:result.latencyMs,httpStatus:result.status},error:result.error,updatedAt:new Date()}).where(eq(syncRuns.id,run.id));await db.insert(auditEvents).values({actor:"admin",action:"litellm.smoke_tested",entityType:"model_deployment",entityId:deployment.id,after:{ok:result.ok,httpStatus:result.status,latencyMs:result.latencyMs},correlationId:id});return NextResponse.json({...result,correlationId:id},{status:result.ok?200:502})}
