"use client";
import { useEffect, useMemo, useState } from "react";
import { StatusHistoryStrip, type StatusHistoryItem } from "@/components/status-history-strip";

type Job={type:string;enabled:boolean;schedule:string;timezone:string;status:string;lastRunAt:string|null;nextRunAt:string|null;durationMs:number|null;failureCount:number;lastError:string|null};
type Source={id:string;name:string;type:string;providerId:string|null;url:string|null;enabled:boolean;priority:number;status:string;discoveredModelCount:number;lastSyncAt:string|null};
type ApiKey={id:string;name:string;prefix:string;scopes:string[];createdAt:string;expiresAt:string|null;lastUsedAt:string|null;revokedAt:string|null};
type Provider={id:string;name:string;status:string;configured:boolean;validated:boolean;lastDiscoveryAt:string|null};
const tabs=["General","LiteLLM","Provider Credentials","API Access","Automation","Model Sources","Discovery Policies","Notifications & Integrations","Security","Advanced / Diagnostics"] as const;
const stamp=(value:string|null|undefined)=>value?new Date(value).toLocaleString():"—";
async function request(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"content-type":"application/json",...init?.headers}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"Request failed");return body;}
function Card({title,children,aside}:{title:string;children:React.ReactNode;aside?:React.ReactNode}){return <section className="panel settings-card"><div className="panel-header"><h3>{title}</h3>{aside}</div><div className="panel-body">{children}</div></section>}
function History({items,label}:{items:StatusHistoryItem[];label:string}){return <div className="history-row"><span>{label}</span><StatusHistoryStrip label={label} items={items.slice(0,14)}/></div>}
export function SettingsClient({initialHistory,smokeHistory,providers}:{initialHistory:StatusHistoryItem[];smokeHistory:StatusHistoryItem[];providers:Provider[]}){
 const [active,setActive]=useState<(typeof tabs)[number]>("General"),[jobs,setJobs]=useState<Job[]>([]),[sources,setSources]=useState<Source[]>([]),[keys,setKeys]=useState<ApiKey[]>([]),[litellm,setLitellm]=useState<Record<string,unknown>>({}),[notice,setNotice]=useState("");
 const refresh=async()=>{try{const [a,b,c,d]=await Promise.all([request("/api/settings/automation"),request("/api/settings/model-sources"),request("/api/settings/api-keys"),request("/api/settings/litellm")]);setJobs(a);setSources(b);setKeys(c);setLitellm(d);}catch(error){setNotice(error instanceof Error?error.message:"Unable to load settings")}};
 useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[]);
 const act=async(fn:()=>Promise<unknown>)=>{try{const result=await fn();setNotice("Saved");await refresh();return result}catch(error){setNotice(error instanceof Error?error.message:"Request failed");return null}};
 const jobHistory=useMemo(()=>initialHistory,[initialHistory]);
 const sourceHistory=(source:Source)=>source.lastSyncAt?[{at:source.lastSyncAt,status:source.status,label:source.name,detail:`${source.discoveredModelCount} discovered models`}]:[];
 return <div className="settings-control-center"><nav className="settings-tabs" aria-label="Settings sections">{tabs.map(tab=><button key={tab} className={active===tab?"active":""} onClick={()=>setActive(tab)}>{tab}</button>)}</nav>{notice&&<p className="demo-banner" role="status">{notice}</p>}
 {active==="General"&&<div className="settings-grid"><Card title="Control plane status"><dl className="definition-list"><dt>Database scheduler</dt><dd>Worker-owned · running independently of n8n</dd><dt>Recent automation</dt><dd><History label="Recent automation history" items={jobHistory}/></dd><dt>System health</dt><dd><History label="Recent health observations" items={smokeHistory}/></dd></dl></Card><Card title="Operating profile"><dl className="definition-list"><dt>Environment</dt><dd>Production Docker stack</dd><dt>n8n dependency</dt><dd>Optional notifications only</dd><dt>History semantics</dt><dd>Squares link to run details when available</dd></dl></Card></div>}
 {active==="Automation"&&<Card title="Automation jobs" aside={<span>Database-backed scheduler</span>}><p className="settings-help">Each job is claimed with a lease before execution, preventing overlap across worker restarts.</p><table className="data-table settings-table"><thead><tr><th>Job</th><th>Enabled</th><th>Schedule</th><th>Next / last run</th><th>Duration / failures</th><th>History</th><th>Actions</th></tr></thead><tbody>{jobs.map(job=><tr key={job.type}><td><strong>{job.type.replaceAll("_"," ")}</strong><br/><small>{job.status}{job.lastError?` · ${job.lastError}`:""}</small></td><td><input aria-label={`${job.type} enabled`} type="checkbox" checked={job.enabled} onChange={event=>void act(()=>request(`/api/settings/automation?type=${job.type}`,{method:"PATCH",body:JSON.stringify({enabled:event.target.checked})}))}/></td><td><input aria-label={`${job.type} cron schedule`} className="input compact-input" defaultValue={job.schedule} onBlur={event=>void act(()=>request(`/api/settings/automation?type=${job.type}`,{method:"PATCH",body:JSON.stringify({schedule:event.target.value})}))}/></td><td><small>Next {stamp(job.nextRunAt)}</small><br/><small>Last {stamp(job.lastRunAt)}</small></td><td>{job.durationMs??"—"} ms<br/>{job.failureCount} failures</td><td><StatusHistoryStrip label={`${job.type} execution history`} items={jobHistory.filter(item=>item.label===job.type)}/></td><td><button onClick={()=>void act(()=>request("/api/settings/automation/run",{method:"POST",body:JSON.stringify({type:job.type})}))}>Run now</button><button onClick={()=>setNotice(`Edit ${job.type} using its schedule field`)}>Configure</button><a className="button" href={`/runs`}>View runs</a></td></tr>)}</tbody></table></Card>}
 {active==="Model Sources"&&<Card title="Model source management" aside={<button onClick={()=>{const name=prompt("Source name");const url=prompt("Source URL (optional for a Manual source)");if(name)void act(()=>request("/api/settings/model-sources",{method:"POST",body:JSON.stringify({name,type:url?"JSON_FEED":"MANUAL",url:url||null,enabled:true,priority:100})}))}}>Add source</button>}><p className="settings-help">Manual sources can be used for a manually entered model inventory; external feeds are tested before sync.</p><table className="data-table settings-table"><thead><tr><th>Source / provider</th><th>Type</th><th>Enabled</th><th>Status</th><th>Last sync / models</th><th>History</th><th>Actions</th></tr></thead><tbody>{sources.map(source=><tr key={source.id}><td><strong>{source.name}</strong><br/><small>{source.url??"Manual source"}</small></td><td>{source.type.replaceAll("_"," ")}</td><td><input aria-label={`${source.name} enabled`} type="checkbox" checked={source.enabled} onChange={event=>void act(()=>request("/api/settings/model-sources",{method:"POST",body:JSON.stringify({...source,enabled:event.target.checked})}))}/></td><td>{source.status}</td><td>{stamp(source.lastSyncAt)}<br/>{source.discoveredModelCount} models</td><td><StatusHistoryStrip label={`${source.name} sync history`} items={sourceHistory(source)}/></td><td><button onClick={()=>void act(()=>request("/api/settings/model-sources/action",{method:"POST",body:JSON.stringify({sourceId:source.id,action:"sync"})}))}>Test / sync now</button><button onClick={()=>{const name=prompt("Source name",source.name);if(name)void act(()=>request("/api/settings/model-sources",{method:"POST",body:JSON.stringify({...source,name})}))}}>Edit</button><button onClick={()=>void act(()=>request(`/api/settings/model-sources?id=${source.id}`,{method:"DELETE"}))}>Delete</button></td></tr>)}</tbody></table><div className="manual-model-form"><strong>Manual model entry</strong><input className="input" placeholder="provider/model-id"/><button onClick={()=>setNotice("Manual model entry is stored through the selected Manual source during discovery")}>Add manual model</button></div></Card>}
 {active==="LiteLLM"&&<Card title="LiteLLM connection" aside={<button onClick={()=>void act(()=>request("/api/settings/litellm",{method:"POST"}))}>Test connection</button>}><div className="settings-grid"><dl className="definition-list"><dt>Base URL</dt><dd>{String(litellm.baseUrl??"Not configured")}</dd><dt>Admin / master credential</dt><dd>{String(litellm.masterKeyHint??"Not configured")}</dd><dt>Connection status</dt><dd>{litellm.lastSuccess?"Connected":"Not tested"}</dd></dl><dl className="definition-list"><dt>Last successful connection</dt><dd>{stamp(litellm.lastSuccess as string|null)}</dd><dt>Version</dt><dd>{String(litellm.version??"Not detected")}</dd><dt>Deployments</dt><dd>{String(litellm.deploymentCount??0)}</dd><dt>Sync status</dt><dd>Inventory sync available from LiteLLM page</dd></dl></div></Card>}
 {active==="Provider Credentials"&&<Card title="Provider credential manager"><table className="data-table settings-table"><thead><tr><th>Provider</th><th>Masked credential</th><th>Status</th><th>Last validation / use</th><th>Actions</th></tr></thead><tbody>{providers.map(provider=><tr key={provider.id}><td><strong>{provider.name}</strong></td><td>{provider.configured?"Configured · encrypted":"Not configured"}</td><td>{provider.validated?"Validated":provider.configured?"Unverified":"Missing"}</td><td>{stamp(provider.lastDiscoveryAt)} / —</td><td><a className="button" href={`/providers/${provider.id}`}>{provider.configured?"Replace / rotate":"Add"}</a><a className="button" href={`/providers/${provider.id}`}>Test</a><button onClick={()=>setNotice(`Disable/delete ${provider.name} from its provider detail`)}>Disable</button><button onClick={()=>setNotice(`Delete ${provider.name} credential from its provider detail`)}>Delete</button></td></tr>)}</tbody></table></Card>}
 {active==="API Access"&&<Card title="RATLLM API keys" aside={<button onClick={()=>{const name=prompt("Key name");if(name)void act(async()=>{const result=await request("/api/settings/api-keys",{method:"POST",body:JSON.stringify({name,scopes:["read","automation"]})});setNotice(`Copy this key now (it will not be shown again): ${result.key}`);return result})}}>Generate key</button>}><table className="data-table settings-table"><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Created / expires</th><th>Last used</th><th>State</th><th>Actions</th></tr></thead><tbody>{keys.map(key=><tr key={key.id}><td>{key.name}</td><td className="mono">{key.prefix}</td><td>{key.scopes.join(", ")}</td><td>{stamp(key.createdAt)}<br/>{stamp(key.expiresAt)}</td><td>{stamp(key.lastUsedAt)}</td><td>{key.revokedAt?"Revoked":"Active"}</td><td><button onClick={()=>void act(()=>request("/api/settings/api-keys",{method:"PATCH",body:JSON.stringify({keyId:key.id,action:"rotate",graceHours:1})}))}>Rotate</button><button onClick={()=>void act(()=>request("/api/settings/api-keys",{method:"PATCH",body:JSON.stringify({keyId:key.id,action:"revoke"})}))}>Revoke</button></td></tr>)}</tbody></table></Card>}
 {active==="Notifications & Integrations"&&<Card title="Optional n8n notifications" aside={<a className="button" href="/n8n">Open n8n integration</a>}><dl className="definition-list"><dt>n8n Base URL</dt><dd>Environment-configured when present</dd><dt>n8n API key</dt><dd>Masked / never returned to the browser</dd><dt>Connection</dt><dd>Use Test connection on the n8n integration page</dd><dt>Workflow</dt><dd>Create RATLLM Notification Workflow from the n8n integration page. It receives events; it never schedules RATLLM.</dd><dt>Delivery history</dt><dd><History label="Recent operational delivery history" items={jobHistory}/></dd></dl></Card>}
 {active==="Discovery Policies"&&<Card title="Discovery policies"><dl className="definition-list"><dt>Candidate verification</dt><dd>Scheduled and direct-provider verified</dd><dt>Manual sources</dt><dd>Allowed and independently syncable</dd><dt>Rate safety factor</dt><dd>70% conservative observed limit</dd></dl></Card>}
 {active==="Security"&&<Card title="Security"><dl className="definition-list"><dt>Provider secrets</dt><dd>AES-256-GCM encrypted at rest</dd><dt>LiteLLM secret</dt><dd>Encrypted at rest and masked in GET responses</dd><dt>RATLLM API keys</dt><dd>SHA-256 hash stored; full token displayed only on creation/rotation</dd></dl></Card>}
 {active==="Advanced / Diagnostics"&&<Card title="Diagnostics"><dl className="definition-list"><dt>Worker</dt><dd>Database scheduler owns execution and leases</dd><dt>Recent run history</dt><dd><History label="Diagnostic run history" items={jobHistory}/></dd><dt>Health monitor</dt><dd><History label="Diagnostic health observations" items={smokeHistory}/></dd></dl></Card>}
 </div>}
